# Generated by Django 5.2.12 on 2026-04-10 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rating',
            name='api_rating_movie_i_417860_idx',
        ),
    ]
