# Generated by Django 5.2.12 on 2026-04-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_rating_api_rating_movie_i_417860_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(blank=True, help_text='URL do poster do filme', max_length=500, null=True),
        ),
    ]
